# suppose if we have multiple task to perform but if the 1st task is failed it won't go to the next task, but with
  # the help of error handling even if the previous task is failed it won't stop the executing there it will go to the
  # next task and it will perform it.

- name: Demo On Error Handling
  hosts: localhost
  tasks:
    - name: Shell Command
      ansible.builtin.shell: lss
      ignore_errors: yes

# Suppose if i give lss command which is not present in place of ls it will end the job there itself it won't go next step
# But if i provide ignore_error as yes then even the first step fail it will go to the next step without stopping the job.
    - name: Print Hello
      ansible.builtin.debug:
        msg: Hello
